

#ifndef __ABS_H
#define __ABS_H
#include "MainTask.h"
/*
#define PLUS_BUTTON_START_X  657
#define PLUS_BUTTON_START_Y  270
#define PLUS_BUTTON_END_X    PLUS_BUTTON_START_X + 61 //718
#define PLUS_BUTTON_END_Y    PLUS_BUTTON_START_Y + 36 //306
*/

extern char AbsCalibration_auto_flag_end;
extern char AbsCalibration_auto_flag;
extern float Used_AbsCali[ABS_CHANNEL_MAX+1][12];  //8???,12???


#define ABS_CHANNEL_BUTTON_START_X  ANALYSIS_FILTER_SELECT_START_X
#define ABS_CHANNEL_BUTTON_START_Y  TITLESBAR_HEIGHT+CONTENTBAR_TITLE_HEIGHT+15   //52+12
#define ABS_CHANNEL_BUTTON_END_X    ABS_CHANNEL_BUTTON_START_X+100
#define ABS_CHANNEL_BUTTON_END_Y    ABS_CHANNEL_BUTTON_START_Y+45//306



#define ABS_PLUS_BUTTON_START_X   ANALYSIS_FILTER_SELECT_START_X-5
#define ABS_PLUS_BUTTON_START_Y   ABS_CHANNEL_BUTTON_END_Y+20   //
#define ABS_PLUS_BUTTON_END_X    (ABS_PLUS_BUTTON_START_X + 61)//
#define ABS_PLUS_BUTTON_END_Y    (ABS_PLUS_BUTTON_START_Y + 36)//
/*
#define MINUS_BUTTON_START_X  PLUS_BUTTON_END_X + 5 //723
#define MINUS_BUTTON_START_Y  PLUS_BUTTON_START_Y //270
#define MINUS_BUTTON_END_X    MINUS_BUTTON_START_X + 61 //784
#define MINUS_BUTTON_END_Y    PLUS_BUTTON_END_Y	//306
*/
#define ABS_MINUS_BUTTON_START_X  ABS_PLUS_BUTTON_END_X + 5 //723
#define ABS_MINUS_BUTTON_START_Y  ABS_PLUS_BUTTON_START_Y	//245
#define ABS_MINUS_BUTTON_END_X    ABS_MINUS_BUTTON_START_X+ 61 //784
#define ABS_MINUS_BUTTON_END_Y    ABS_PLUS_BUTTON_END_Y //306


#define ABS_AUTO_BUTTON_START_X  ANALYSIS_FILTER_SELECT_START_X
#define ABS_AUTO_BUTTON_START_Y  ABS_PLUS_BUTTON_END_Y+20
#define ABS_AUTO_BUTTON_END_X    ABS_AUTO_BUTTON_START_X+100
#define ABS_AUTO_BUTTON_END_Y    ABS_AUTO_BUTTON_START_Y +45//306


void  ClearAutoCaliFlag(void);
void AbsCalibration_Interface(void);
void AbsCalibration_Go(void);
void AbsCalibration_Scan(void);
#endif
