
#ifndef __DISPLAY_STR_H
#define __DISPLAY_STR_H

//#define CALIBRATOR_CONCENTRATION_MAX 12
//设置浓度界面
//#define CALIBRATOR_CONCENTRATION_UNIT_MAX 7
//#define CALIBRATOR_CONCENTRATION_UNIT_CHAR_MAX 8



//1.Main Menu
extern const char STR_FILTER[LANGUAGE_TYPES][20] ;
extern const char STR_MODE[LANGUAGE_TYPES][20] ;
extern const char STR_OFF[LANGUAGE_TYPES][8] ;
extern const char STR_MODE_NORMAL[LANGUAGE_TYPES][10] ;
extern const char STR_MODE_FAST[LANGUAGE_TYPES][10];

extern const char SETUP_SHAKE_SHAKE[LANGUAGE_TYPES][20] ;
extern const char SETUP_SHAKE_SPEED[LANGUAGE_TYPES][20] ;
extern const char SETUP_SHAKE_TIME[LANGUAGE_TYPES][20];

extern const char STR_SHAKE_SPEED_SLOW[LANGUAGE_TYPES][15] ;
extern const char STR_SHAKE_SPEED_NORMAL[LANGUAGE_TYPES][15] ;
extern const char STR_SHAKE_SPEED_FAST[LANGUAGE_TYPES][15];

extern const char STR_OPEN[LANGUAGE_TYPES][10] ;
extern const char STR_CLOSE[LANGUAGE_TYPES][10];
extern const char STR_NO[LANGUAGE_TYPES][10];

extern const char STR_LAYOUT_NAME[LANGUAGE_TYPES][40] ;
extern const char STR_LAYOUT[LANGUAGE_TYPES][LANGUAGE_CHAR_MAX];// = {"Layout","布局"};

extern const char STR_PREPROCESS[LANGUAGE_TYPES][20];
extern const char STR_KINETIC[LANGUAGE_TYPES][20];
extern const char STR_CURVE[LANGUAGE_TYPES][20] ;




//Interpret
extern const char STR_INTERPRET[LANGUAGE_TYPES][LANGUAGE_CHAR_MAX];
extern const char STR_ABS[LANGUAGE_TYPES][10];
extern const char STR_CONC[LANGUAGE_TYPES][10];
extern const char STR_CUTOFF[LANGUAGE_TYPES][10];



//设置浓度界面
extern const char STR_CONCENTRATION_SELECT_UNIT[CALIBRATOR_CONCENTRATION_UNIT_MAX][10];


extern const char STR_TABLE_RECORD_NO[LANGUAGE_TYPES][10];



//Quality
extern const char STR__PASS[LANGUAGE_TYPES][10];
extern const char STR__FAILED[LANGUAGE_TYPES][10];


//Run
extern const char STR_CURRENT_CYCLE[LANGUAGE_TYPES][20];
extern const char RUN_COMMAND_RESPONSE_ERROR[LANGUAGE_TYPES][RUN_ERROR_CHAR_MAX];


//Report
extern const char FILE_IMPORT_SUCCESS[LANGUAGE_TYPES][RUN_ERROR_CHAR_MAX];
extern const char FILE_IMPORT_ERROR[LANGUAGE_TYPES][RUN_ERROR_CHAR_MAX];
extern const char FILE_EXPORT_SUCCESS[LANGUAGE_TYPES][RUN_ERROR_CHAR_MAX];
extern const char FILE_EXPORT_ERROR[LANGUAGE_TYPES][RUN_ERROR_CHAR_MAX];

extern const char STR_RESTART_SYSTEM[LANGUAGE_TYPES][RUN_ERROR_CHAR_MAX];
extern const char STR_NO_FILE[LANGUAGE_TYPES][RUN_ERROR_CHAR_MAX];
extern const char STR_MODIFIED_FILE[LANGUAGE_TYPES][RUN_ERROR_CHAR_MAX];
extern const char STR_ALL[LANGUAGE_TYPES][RUN_ERROR_CHAR_MAX];
extern const char STR_WAIT[LANGUAGE_TYPES][RUN_ERROR_CHAR_MAX];
extern const char STR_PRINT_WAIT_MESSAGE[LANGUAGE_TYPES][RUN_ERROR_CHAR_MAX];


//质控
extern const char STR_QUALITY_TITLE[LANGUAGE_TYPES][LANGUAGE_CHAR_MAX];
extern const char STR_QUALITY_RESULT[LANGUAGE_TYPES][2][10];
extern const char REFERENCE_SELECT[LANGUAGE_TYPES][2][10];

extern const char QUALITY_TABLE_RESULT[LANGUAGE_TYPES][10];
extern const char QUALITY_MAIN_TITLE[LANGUAGE_TYPES][30];
extern const char QUALITY_TABLE_TARGET[LANGUAGE_TYPES][15];
extern const char QUALITY_TABLE_SD[LANGUAGE_TYPES][15];
extern const char QUALITY_TABLE_CV[LANGUAGE_TYPES][15];
extern const char QUALITY_TABLE_UPPER_LIMIT[LANGUAGE_TYPES][15];
extern const char QUALITY_TABLE_LOWER_LIMIT[LANGUAGE_TYPES][15];


//
extern const char STR_NAND_FULL[LANGUAGE_TYPES][RUN_ERROR_CHAR_MAX];
#endif







