
#define INTERPRET_1_START_X  19
#define INTERPRET_1_START_Y  144
#define INTERPRET_1_END_X    120
#define INTERPRET_1_END_Y    190

#define INTERPRET_1_R_START_X  120
#define INTERPRET_1_R_START_Y  144
#define INTERPRET_1_R_END_X    210
#define INTERPRET_1_R_END_Y    190


#define INTER_SEL_WIDTH      60

#define INTERPRET_EXPAND1_START_X  INTERPRET_1_R_START_X
#define INTERPRET_EXPAND1_START_Y  144
#define INTERPRET_EXPAND1_END_X  (INTERPRET_EXPAND1_START_X + 170)
#define INTERPRET_EXPAND1_END_Y  190

#define INTERPRET_EXPAND2_START_X  INTERPRET_2_R_START_X
#define INTERPRET_EXPAND2_START_Y  209
#define INTERPRET_EXPAND2_END_X  (INTERPRET_EXPAND2_START_X + 170)
#define INTERPRET_EXPAND2_END_Y  255

#define INTERPRET_2_START_X  19
#define INTERPRET_2_START_Y  209
#define INTERPRET_2_END_X    120
#define INTERPRET_2_END_Y    255

#define INTERPRET_2_R_START_X  120
#define INTERPRET_2_R_START_Y  209
#define INTERPRET_2_R_END_X    210
#define INTERPRET_2_R_END_Y    255

#define INTERPRET_EDIT_COEF1_START_X  160//105
#define INTERPRET_EDIT_COEF1_START_Y  (INTERPRET_2_R_END_Y + 19)
#define INTERPRET_EDIT_COEF1_END_X  (INTERPRET_EDIT_COEF1_START_X + 80)
#define INTERPRET_EDIT_COEF1_END_Y  (INTERPRET_EDIT_COEF1_START_Y + 27)

#define INTERPRET_EDIT_COEF2_START_X  290
#define INTERPRET_EDIT_COEF2_START_Y  (INTERPRET_2_R_END_Y + 19)
#define INTERPRET_EDIT_COEF2_END_X  (INTERPRET_EDIT_COEF2_START_X + 80)
#define INTERPRET_EDIT_COEF2_END_Y  (INTERPRET_EDIT_COEF2_START_Y + 27)

#define INTERPRET_EDIT_COEF3_START_X  80//395
#define INTERPRET_EDIT_COEF3_START_Y  (INTERPRET_2_R_END_Y + 19)
#define INTERPRET_EDIT_COEF3_END_X  (INTERPRET_EDIT_COEF3_START_X + 80)
#define INTERPRET_EDIT_COEF3_END_Y  (INTERPRET_EDIT_COEF3_START_Y + 27)

#define INTERPRET_EDIT_COEF4_START_X  110//220
#define INTERPRET_EDIT_COEF4_START_Y  (INTERPRET_EDIT_COEF3_END_Y + 19)
#define INTERPRET_EDIT_COEF4_END_X  (INTERPRET_EDIT_COEF4_START_X + 100)
#define INTERPRET_EDIT_COEF4_END_Y  (INTERPRET_EDIT_COEF4_START_Y + 27)

#define INTERPRET_EDIT_COEF5_START_X  80
#define INTERPRET_EDIT_COEF5_START_Y  (INTERPRET_EDIT_COEF4_END_Y + 19)
#define INTERPRET_EDIT_COEF5_END_X  (INTERPRET_EDIT_COEF5_START_X + 80)
#define INTERPRET_EDIT_COEF5_END_Y  (INTERPRET_EDIT_COEF5_START_Y + 27)

#define EDIT_BOX_WIDTH  58



//DN位置定义
//LIMIT
#define INTERPRET_EDIT_COEF1_START_X_DN  130
#define INTERPRET_EDIT_COEF1_START_Y_DN  (INTERPRET_EDIT_COEF1_START_Y)
#define INTERPRET_EDIT_COEF1_END_X_DN    (INTERPRET_EDIT_COEF1_START_X_DN+80)
#define INTERPRET_EDIT_COEF1_END_Y_DN    (INTERPRET_EDIT_COEF1_END_Y)

//阳性条件>
#define INTERPRET_EDIT_COEF2_START_X_DN  (INTERPRET_EDIT_COEF1_START_X_DN)
#define INTERPRET_EDIT_COEF2_START_Y_DN  (INTERPRET_EDIT_COEF4_START_Y)
#define INTERPRET_EDIT_COEF2_END_X_DN    (INTERPRET_EDIT_COEF1_END_X_DN)
#define INTERPRET_EDIT_COEF2_END_Y_DN    (INTERPRET_EDIT_COEF4_END_Y)
//弱阳性>
#define INTERPRET_EDIT_COEF3_START_X_DN  (INTERPRET_EDIT_COEF1_START_X_DN)
#define INTERPRET_EDIT_COEF3_START_Y_DN  (INTERPRET_EDIT_COEF5_START_Y)
#define INTERPRET_EDIT_COEF3_END_X_DN    (INTERPRET_EDIT_COEF1_END_X_DN)
#define INTERPRET_EDIT_COEF3_END_Y_DN    (INTERPRET_EDIT_COEF5_END_Y)


//定性模式扩展选中的宽度
#define INTER_MODE_EXPAND_WIDTH1        65
#define INTER_MODE_EXPAND_WIDTH2        70
#define INTER_MODE_EXPAND_WIDTH         (INTER_MODE_EXPAND_WIDTH1+INTER_MODE_EXPAND_WIDTH2+5)



//模式
enum
{
    INTER_NORMAL=0, //普通
    INTER_SPECIAL   //特
};


#ifndef __PROTOCOL_INTER_H
#define __PROTOCOL_INTER_H

extern const char STR_INTERPRET_POS[LANGUAGE_TYPES][20];// = {"Positive:", "阳性条件："};
extern const char STR_INTERPRET_WEAK_POS[LANGUAGE_TYPES][100];// = {"Weak P: (+/- Cutoff%)", "弱阳性：(+/- 临界值%)"};

extern const char STR_INTERPRET_SOURCE[LANGUAGE_TYPES][15];// = {"Source", "数据源"};
extern const char STR_INTERPRET_CUTOFF[LANGUAGE_TYPES][15];// = {"Cutoff:", "临界值："};

//DN增加
extern const char STR_INTERPRET_POS_DN[LANGUAGE_TYPES][20];  //DN增加
extern const char STR_INTERPRET_WEAK_POS_DN[LANGUAGE_TYPES][40];//DN增加
extern const char STR_INTERPRET_LIMIT_DN[LANGUAGE_TYPES][20];//DN增加
extern const char STR_INTER_MODE[LANGUAGE_TYPES][2][15];//DN增加





void ProtocolInter_Interface(void);
void ProtocolInter_Scan(void);
void ProtocolInter_Go(void);
#endif
