/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: FontChinese16.c                                       *
* Font:        Î¢ÈíÑÅºÚ                                              *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: D:\1. Product\AS112\9.Software\2.ARM\Source\FontMed.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFontChinese16;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontFontChinese16_5149[ 32] = { /* code 5149 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _____X__,________,
  _XX__X__,X_______,
  ___X_XXX,________,
  _____X__,________,
  XXXXXXXX,XX______,
  ___X__X_,________,
  ___X__X_,_X______,
  __X___X_,_X______,
  XX____XX,XX______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontChinese16_65E0[ 32] = { /* code 65E0 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  XXXXXXXX,X_______,
  ____X___,________,
  ___X____,________,
  XXXXXXXX,XX______,
  ___X____,________,
  __X__X__,________,
  __X__X__,_X______,
  XX___X__,_X______,
  _____XXX,XX______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontChinese16_6EE4[ 32] = { /* code 6EE4 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  _X___X__,________,
  __X__XXX,XX______,
  X__XXXXX,XX______,
  _X_XXXXX,________,
  ___X_X__,X_______,
  _X_X_XXX,X_______,
  _X_XXXXX,________,
  X_XX_X__,XX______,
  X_X__XXX,X_______,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontChinese16_7247[ 32] = { /* code 7247 */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  __X____X,________,
  __X____X,________,
  __X____X,________,
  __XXXXXX,XX______,
  __X_____,________,
  __XXXXXX,________,
  __X____X,________,
  _XX____X,________,
  _X_____X,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontFontChinese16_CharInfo[4] = {
   {  10,  10,  2, acGUI_FontFontChinese16_5149 } /* code 5149 */
  ,{  10,  10,  2, acGUI_FontFontChinese16_65E0 } /* code 65E0 */
  ,{  10,  10,  2, acGUI_FontFontChinese16_6EE4 } /* code 6EE4 */
  ,{  10,  10,  2, acGUI_FontFontChinese16_7247 } /* code 7247 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontChinese16_Prop4 = {
   0x7247 /* first character */
  ,0x7247 /* last character  */
  ,&GUI_FontFontChinese16_CharInfo[  3] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontChinese16_Prop3 = {
   0x6EE4 /* first character */
  ,0x6EE4 /* last character  */
  ,&GUI_FontFontChinese16_CharInfo[  2] /* address of first character */
  ,&GUI_FontFontChinese16_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontChinese16_Prop2 = {
   0x65E0 /* first character */
  ,0x65E0 /* last character  */
  ,&GUI_FontFontChinese16_CharInfo[  1] /* address of first character */
  ,&GUI_FontFontChinese16_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontChinese16_Prop1 = {
   0x5149 /* first character */
  ,0x5149 /* last character  */
  ,&GUI_FontFontChinese16_CharInfo[  0] /* address of first character */
  ,&GUI_FontFontChinese16_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFontChinese16 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFontChinese16_Prop1}
  ,12 /* Baseline */
  ,5 /* Height of lowercase characters */
  ,8 /* Height of capital characters */
};

